@GymApi_HostAddress = http://localhost:5225

GET {{GymApi_HostAddress}}/api/members/ 
Accept: application/json

###

GET {{GymApi_HostAddress}}/api/memberroutines/
Accept: application/json

###

GET {{GymApi_HostAddress}}/api/bookingclasses/
Accept: application/json

###

POST {{GymApi_HostAddress}}/api/members/login
Content-Type: application/json



###

GET {{GymApi_HostAddress}}/api/asistencias/
Accept: application/json

###

